spring.application.name=odontologia_api
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/odontologia_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/La_Paz

spring.jackson.time-zone=America/La_Paz

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:true}

security.jwt.secret=${JWT_SECRET:ZXN0ZS1lcy11bi1zZWNyZXRvLXN1ZmljaWVudGVtZW50ZS1sYXJnby1wYXJhLW9yYWxkZW50LWFwaS0yMDI2}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

cloudinary.enabled=${CLOUDINARY_ENABLED:false}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
cloudinary.max-file-size-bytes=${CLOUDINARY_MAX_FILE_SIZE_BYTES:5242880}

app.seed.enabled=${APP_SEED_ENABLED:false}
